### ISSUE TITLE
External interrupts does not work for me

### ISSUE THREAD

**Issue by pongraczi** [roboard/86Duino_Linux_SDK#1]
Hi,
I did a test using a simple program, shown below.
It just not work.
I assume somehow the external interrupts does not work in the SDK.

Am I right?

Sample program:
```cpp
#include

const byte ledPin = LED_BUILTIN;
const byte interruptPin = 42;
volatile byte state = LOW;

void blink() {
state = !state;
}

void setup() {
pinMode(ledPin, OUTPUT);
pinMode(interruptPin, INPUT);
attachInterrupt(0, blink, CHANGE);
}

void loop() {
digitalWrite(ledPin, state); delay(1);
}

int main() {
setup();
while (1)
loop();
}
```

**Comment by roboard** [comment]
Hi,
I used your code on 86Duino and run it with 86Duino Linux SDK, I got this: https://reurl.cc/GV96zW
In video, I connect one "GROUND" wire to touch with "interruptPin" (pin42) and the LED (pin13) will blink.
When I print "state" value and connect the "GROUND" pin to pin42, get "state" is 0, and get 1 when disconnect it.
On the other word,  always get 1 when pin42 is not connected with anything, try to use one "GROUND" wire to touch with pin42 ;)

**Comment by pongraczi** [comment]
Hmmm, whadda.....  Thank you very much for your time and video.
Something definitely not ok on my side.

Did you compile it with the SDK and run under linux?

I use buildroot to build up a linux and I run these tests on my One.
I got very strange result, cloning your test case:
* pin 42 (int.0): absolutely nothing happens
* pin 43 (int.1): led is flickering, independently, what I put on the pin: static ground / static 5V or just left it in tri-state (left empty)
* pin 44 (int.2): is the same as pin 43.
Check it here: https://youtu.be/7bjHSY1UQV0

(Notes: you can see an Uno for reference, they are connected to the same input and should react exactly the same, but as you can see, Uno is ok, but somehow the One ignores the input and behave differently. For me it seems the real input on pins does not trigger the interrupts, but something else overrides them.)

**Comment by pongraczi** [comment]
Ok, seems there was a sideffect on my side.  
Long story:
We use 86duino based control units for years now successfully, but some features of 86duino we did not use before.  
As I reported earlier, we had problems with cpu load until you fixed it and due to that I made a workaround on the previous SDK.  
So, as I started my One, it always started a program, which built on the older, modified SDK and I had to stop that program, before I started the test program.  
I just removed the autostart from the old program and rebooted my One, and it seems it is working.  

So, I assume, the old SDK based software initialized the crossbar (or something like this) and it fixed for that session and even I stopped that software, the new test program was not able to reinit/use the hardware.   

It is only a theory, based on my experience only.  

Is it possible the first program which initialize the crossbar (arduino) will fix the actual configuration and other programs run later will not be able reconfigure it? Or I missed something?

**Comment by roboard** [comment]
Thanks for your response. 
Actually, the interrupt pin use the different function from GPIO called "mcm", so it will be switched to "mcm" function automatically after calling "attachInterrupt()", so it will not be GPIO INPUT pin, but "mcm" pin.
If your another old program always call digitalRead(interruptPIN), that will switch it from mcm to GPIO again (or call it after attachInterrupt()), the interrupt pin will not be able to work, if so, try to comment "digitalRead(interruptPIN)".
(Note: Don't input 5V to GPIO INPUT pin, use 3.3V instead.)

**Comment by pongraczi** [comment]
Thanks for the hint, I revise my codes. Normally I do not read read interrupt pins with digitalread().
Anyway, as I read the Encoder library, I expected that, several class functions are not available under linux, only under dos.  
Similarly, the time resolution of the encoder is worse under linux than under dos (readnanoseconds for example does not exist due to ifdef compile time condition during SDK compilation).  
Are there specific differences between the native 86duino (I mean, using 86duino ide and the board as an arduino clone) and the SDK on linux?  (Yeah, I can search the source code for ifdefs).

Regarding to 5V vs. 3.3, I know, the 5V tolerant is not the same as native 5V :)

**Comment by roboard** [comment]
OK, a important point different from Linux 86Duino SDK and DOS 86Duino lib is "Real-time requirement".
For Linux, a Multi-processing OS, some DOS libraries have higher real-time requirement like "SoftwareSerial", "OneWire", "Irremote", those libraries will not be in Linux SDK because the value getting from the sensor will be inaccurate or incorrect, some function(like "readNanoseconds") that may get incorrect result also be removed from Linux SDK.
In the other word, only the function that can get accurate value and work fine will be stay in Linux SDK.
In addition, note that we don't use any 86Duino driver to access I/O device under Linux, for interrupt, we poll I/O registers to do it in another thread, so the interrupt event also is lower real-time, those libraries need high frequency interrupt response also were removed from Linux SDK.

**Comment by pongraczi** [comment]
Thanks, that explains what I saw in the SDK sourcecode and what I experienced when I was trying to use rcswitch on linux.  
So, I ended up with a hybrid configuration: arduino nano to handle rcswitch --- rs232 --- 86duino with control system on linux.  
Thank you for the info.
